version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-75-101-138-165.compute-1.amazonaws.com
            port: '5432'
            database: de39289tvrhdp6
            user: latmhhskkucqsd
            password: d4e9abe22a9942e88b5c7bf331969b6a758beca9e152d3b760477916f441adb5
            migrations: true
            ssl: true